name: brepgen_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aiohttp=3.9.5=py39h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - arrow-cpp=16.1.0=hc1eb8f0_0
  - async-timeout=4.0.3=py39h06a4308_0
  - attrs=23.1.0=py39h06a4308_0
  - aws-c-auth=0.6.19=h5eee18b_0
  - aws-c-cal=0.5.20=hdbd6064_0
  - aws-c-common=0.8.5=h5eee18b_0
  - aws-c-compression=0.2.16=h5eee18b_0
  - aws-c-event-stream=0.2.15=h6a678d5_0
  - aws-c-http=0.6.25=h5eee18b_0
  - aws-c-io=0.13.10=h5eee18b_0
  - aws-c-mqtt=0.7.13=h5eee18b_0
  - aws-c-s3=0.1.51=hdbd6064_0
  - aws-c-sdkutils=0.1.6=h5eee18b_0
  - aws-checksums=0.1.13=h5eee18b_0
  - aws-crt-cpp=0.18.16=h6a678d5_0
  - aws-sdk-cpp=1.10.55=h721c034_0
  - blas=1.0=mkl
  - boost-cpp=1.82.0=hdb19cb5_2
  - bottleneck=1.3.7=py39ha9d4c09_0
  - brotli=1.0.9=h5eee18b_8
  - brotli-bin=1.0.9=h5eee18b_8
  - brotli-python=1.0.9=py39h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.7.4=hbcca054_0
  - certifi=2024.7.4=pyhd8ed1ab_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - contourpy=1.2.0=py39hdb19cb5_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cuda-version=12.5=3
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - datasets=2.19.1=py39h06a4308_0
  - dbus=1.13.18=hb2f20db_0
  - dill=0.3.8=py39h06a4308_0
  - expat=2.6.2=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py39h06a4308_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_2
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.51.0=py39h5eee18b_0
  - freeimage=3.18.0=h66f5774_11
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.4.0=py39h5eee18b_0
  - fsspec=2024.3.1=py39h06a4308_0
  - gflags=2.2.2=h6a678d5_1
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - glog=0.5.0=h6a678d5_1
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py39heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - huggingface_hub=0.23.1=py39h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py39h06a4308_0
  - imath=3.1.6=h6239696_1
  - importlib-metadata=7.0.1=py39h06a4308_0
  - importlib_resources=6.4.0=py39h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py39h06a4308_0
  - joblib=1.4.2=py39h06a4308_0
  - jpeg=9e=h5eee18b_2
  - jxrlib=1.1=hd590300_3
  - kiwisolver=1.4.4=py39h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.10.1.7=0
  - libcups=2.4.2=h2d74bed_1
  - libcurand=10.3.6.82=0
  - libcurl=8.7.1=h251f7ec_0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=14.1.0=h77fa898_0
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=14.1.0=h77fa898_0
  - libgrpc=1.62.2=h2d74bed_0
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libllvm14=14.0.6=hdb19cb5_3
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - libprotobuf=4.25.3=he621ea3_0
  - libraw=0.20.2=h10796ff_1
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx-ng=14.1.0=hc0a3c3a_0
  - libtasn1=4.19.0=h5eee18b_0
  - libthrift=0.15.0=h1795dd8_2
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.4=hfdd30dd_2
  - libzlib=1.2.13=h4ab18f5_6
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py39h5eee18b_0
  - matplotlib=3.8.4=py39h06a4308_0
  - matplotlib-base=3.8.4=py39h1128e8f_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.8=py39h5eee18b_0
  - mkl_random=1.2.4=py39hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py39h06a4308_0
  - multidict=6.0.4=py39h5eee18b_0
  - multiprocess=0.70.15=py39h06a4308_0
  - mysql=5.7.24=h721c034_2
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.2.1=py39h06a4308_0
  - numexpr=2.8.7=py39h85018f9_0
  - numpy=1.26.4=py39h5f9d8c6_0
  - numpy-base=1.26.4=py39hb5e798b_0
  - occt=7.8.1=novtk_h44cb049_102
  - openexr=3.1.5=h0cdce71_2
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.3.1=h4bc722e_2
  - orc=2.0.1=h2d29ad5_0
  - packaging=24.1=py39h06a4308_0
  - pandas=2.2.2=py39h6a678d5_0
  - pcre2=10.42=hebb0a14_1
  - pillow=10.4.0=py39h5eee18b_0
  - pip=24.0=py39h06a4308_0
  - ply=3.11=py39h06a4308_0
  - pyarrow=16.1.0=py39h1128e8f_0
  - pybind11-abi=4=hd3eb1b0_1
  - pyparsing=3.0.9=py39h06a4308_0
  - pyqt=5.15.10=py39h6a678d5_0
  - pyqt5-sip=12.13.0=py39h5eee18b_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.19=h955ad1f_1
  - python-dateutil=2.9.0post0=py39h06a4308_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python-xxhash=2.0.2=py39h5eee18b_1
  - python_abi=3.9=2_cp39
  - pythonocc-core=7.8.1=novtk_hf9d1935_100
  - pytorch=2.4.0=py3.9_cuda11.8_cudnn9.1.0_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py39h06a4308_0
  - pyyaml=6.0.1=py39h5eee18b_0
  - qt-main=5.15.2=h53bd1ea_10
  - rapidjson=1.1.0.post20240409=hac33072_1
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - regex=2023.10.3=py39h5eee18b_0
  - requests=2.32.3=py39h06a4308_0
  - s2n=1.3.27=hdbd6064_0
  - safetensors=0.4.2=py39ha89cbab_1
  - scikit-learn=1.4.2=py39h1128e8f_1
  - scipy=1.13.1=py39h5f9d8c6_0
  - setuptools=69.5.1=py39h06a4308_0
  - sip=6.7.12=py39h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.10=h6a678d5_1
  - sqlite=3.45.3=h5eee18b_0
  - svgwrite=1.4.3=pyhd8ed1ab_0
  - sympy=1.12=py39h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=3.5.0=py39h2f386ee_0
  - tk=8.6.14=h39e8969_0
  - tokenizers=0.19.1=py39hff361bb_0
  - tomli=2.0.1=py39h06a4308_0
  - torchaudio=2.4.0=py39_cu118
  - torchtriton=3.0.0=py39
  - torchvision=0.19.0=py39_cu118
  - tornado=6.4.1=py39h5eee18b_0
  - tqdm=4.66.4=py39h2f386ee_0
  - transformers=4.41.2=py39h06a4308_0
  - typing-extensions=4.11.0=py39h06a4308_0
  - typing_extensions=4.11.0=py39h06a4308_0
  - tzdata=2024a=h04d1e81_0
  - unicodedata2=15.1.0=py39h5eee18b_0
  - urllib3=2.2.2=py39h06a4308_0
  - utf8proc=2.6.1=h5eee18b_1
  - wheel=0.43.0=py39h06a4308_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxt=1.3.0=hd590300_1
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xxhash=0.8.0=h7f8727e_3
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.9.3=py39h5eee18b_0
  - zipp=3.17.0=py39h06a4308_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.5=hc292b87_2
  - pip:
      - accelerate==0.33.0
      - chamferdist==1.0.3
      - click==8.1.7
      - diffusers==0.27.0
      - docker-pycreds==0.4.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - occwl==2.1.0
      - platformdirs==4.2.2
      - plyfile==1.0.3
      - protobuf==5.27.2
      - psutil==6.0.0
      - sentry-sdk==2.11.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - trimesh==4.4.3
      - wandb==0.17.5
prefix: /home/jaydeep/miniconda3/envs/brepgen_env
